blobs_path: blobs
blobs_storage: FILESYSTEM
cache: cache
calculate_md5: false
create_image_clip_from_videos: false
dangerous_allow_public_without_auth: "false"
database: stash-go.sqlite
ffmpeg_path: ""
ffprobe_path: ""
gallery_cover_regex: (poster|cover|folder|board)\.[^\.]+$
generated: generated
host: 0.0.0.0
jwt_secret_key: f53e48d29b2bb8c020ea67505b7362def33672ae5370391ca3961d63bd00ae69
menu_items:
    - scenes
    - images
    - groups
    - markers
    - galleries
    - performers
    - studios
    - tags
no_proxy: localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
nobrowser: false
notifications_enabled: true
parallel_tasks: 1
plugins:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScripts/stable/index.yml
plugins_path: /home/boom/stash/plugins
port: 9999
preview_audio: true
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScrapers/stable/index.yml
scrapers_path: /home/boom/stash/scrapers
security_tripwire_accessed_from_public_internet: ""
sequential_scanning: false
session_store_key: bfa4508b68959a1ade7516b38a62f89e48050b7ff7d45e0739419d2099a494d6
show_one_time_moved_notification: false
sound_on_preview: false
stash:
    - excludeimage: false
      excludevideo: false
      path: /mnt/d/Movies
theme_color: '#202b33'
ui:
    frontPageContent:
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_released_objects
            values:
                objects: Scenes
          mode: SCENES
          sortBy: date
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_added_objects
            values:
                objects: Studios
          mode: STUDIOS
          sortBy: created_at
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_released_objects
            values:
                objects: Groups
          mode: GROUPS
          sortBy: date
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_added_objects
            values:
                objects: Performers
          mode: PERFORMERS
          sortBy: created_at
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_released_objects
            values:
                objects: Galleries
          mode: GALLERIES
          sortBy: date
    lastNoteSeen: 20240826
video_file_naming_algorithm: OSHASH
write_image_thumbnails: true
