package subtitle

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/stashapp/stash/pkg/file/video"
	"github.com/stashapp/stash/pkg/fsutil"
	"github.com/stashapp/stash/pkg/logger"
	"github.com/stashapp/stash/pkg/models"
)

// Service provides subtitle generation functionality
type Service struct {
	config        *SubtitleConfig
	whisperClient *WhisperClient
	ffmpegPath    string
	mutex         sync.RWMutex
}

// NewService creates a new subtitle service
func NewService(config *SubtitleConfig) *Service {
	s := &Service{
		config: config,
	}
	s.initClients()
	return s
}

func (s *Service) initClients() {
	if s.config == nil {
		return
	}
	timeout := time.Duration(s.config.Timeout) * time.Second

	// Initialize Whisper client
	if s.config.WhisperEnabled && s.config.WhisperURL != "" {
		s.whisperClient = NewWhisperClient(s.config.WhisperURL, timeout)
	}
}

// UpdateConfig updates the service configuration
func (s *Service) UpdateConfig(config *SubtitleConfig) {
	s.mutex.Lock()
	defer s.mutex.Unlock()

	s.config = config
	s.initClients()
}

// GetConfig returns the current configuration
func (s *Service) GetConfig() *SubtitleConfig {
	s.mutex.RLock()
	defer s.mutex.RUnlock()

	return s.config
}

// SetFFmpegPath sets the path to ffmpeg executable
func (s *Service) SetFFmpegPath(path string) {
	s.mutex.Lock()
	defer s.mutex.Unlock()
	s.ffmpegPath = path
}

// GenerateSubtitleResult holds the result of subtitle generation
type GenerateSubtitleResult struct {
	Success      bool   `json:"success"`
	SubtitlePath string `json:"subtitle_path"`
	Language     string `json:"language"`
	Message      string `json:"message"`
}

// GenerateSubtitle generates a subtitle for the given scene
// It first tries to fetch from OpenSubtitles, then falls back to Whisper generation
func (s *Service) GenerateSubtitle(ctx context.Context, scene *models.Scene, language string) (*GenerateSubtitleResult, error) {
	s.mutex.RLock()
	config := s.config
	whisperClient := s.whisperClient
	ffmpegPath := s.ffmpegPath
	s.mutex.RUnlock()

	if config == nil || !config.Enabled {
		return nil, ErrSubtitleDisabled
	}

	if language == "" {
		language = config.DefaultLanguage
	}

	// Get video file path
	videoPath := scene.Path
	if videoPath == "" {
		return nil, ErrNoVideoFile
	}

	// Check if subtitle already exists
	subtitlePath := getSubtitlePath(videoPath)
	if config.SkipIfExists {
		if s.HasSubtitle(scene) {
			return &GenerateSubtitleResult{
				Success:      true,
				SubtitlePath: subtitlePath,
				Language:     language,
				Message:      "subtitle already exists",
			}, nil
		}
	}

	// Generate with Whisper
	if !config.WhisperEnabled || whisperClient == nil {
		return nil, fmt.Errorf("no subtitle source available: Whisper is disabled")
	}

	return s.generateWithWhisper(ctx, videoPath, subtitlePath, language, config.WhisperTranslate, whisperClient, ffmpegPath)
}

// generateWithWhisper generates subtitles using Whisper
func (s *Service) generateWithWhisper(ctx context.Context, videoPath, subtitlePath, language string, translate bool, client *WhisperClient, ffmpegPath string) (*GenerateSubtitleResult, error) {
	// Check Whisper service availability
	if err := client.HealthCheck(ctx); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrWhisperUnavailable, err)
	}

	// Extract audio from video
	audioPath, err := s.extractAudio(ctx, videoPath, ffmpegPath)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrAudioExtractFailed, err)
	}
	defer os.Remove(audioPath) // Clean up temp audio file

	mode := "transcribe"
	if translate {
		mode = "translate to English"
	}
	logger.Infof("Extracted audio to %s, sending to Whisper (%s)...", audioPath, mode)

	// Transcribe/translate audio using async API
	// Notice: Always request JSON and handle formatting inside Go
	result, err := client.TranscribeAsync(ctx, audioPath, language, translate, "json")
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrTranscribeFailed, err)
	}

	finalContent := result.Content
	if s.config.WhisperAINormalize {
		logger.Infof("Using Mistral AI to smartly normalize subtitle chunks for %s", filepath.Base(videoPath))
		alignedSrt, alignErr := generateAIAlignedSRT(ctx, result.Content)
		if alignErr != nil {
			logger.Warnf("AI Alignment pipeline failed: %v", alignErr)
			finalContent = generateBasicSRT(result.Content)
		} else {
			finalContent = alignedSrt
		}
	} else {
		finalContent = generateBasicSRT(result.Content)
	}

	// Save subtitle file
	if err := os.WriteFile(subtitlePath, []byte(finalContent), 0644); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrSaveSubtitleFailed, err)
	}

	msg := "subtitle generated by Whisper"
	if translate {
		msg = "subtitle translated to English by Whisper"
	}
	logger.Infof("Subtitle generated by Whisper and saved to %s", subtitlePath)

	return &GenerateSubtitleResult{
		Success:      true,
		SubtitlePath: subtitlePath,
		Language:     result.Language,
		Message:      msg,
	}, nil
}

// getSubtitlePath returns the subtitle file path for a video
func getSubtitlePath(videoPath string) string {
	ext := filepath.Ext(videoPath)
	basePath := strings.TrimSuffix(videoPath, ext)
	return basePath + ".srt"
}

// extractAudio extracts audio from video file using ffmpeg
func (s *Service) extractAudio(ctx context.Context, videoPath string, ffmpegPath string) (string, error) {
	if ffmpegPath == "" {
		ffmpegPath = "ffmpeg"
	}

	// Create temp file for audio
	tempDir := os.TempDir()
	audioFileName := fmt.Sprintf("stash_audio_%d.mp3", time.Now().UnixNano())
	audioPath := filepath.Join(tempDir, audioFileName)

	// Build ffmpeg command
	args := []string{
		"-i", videoPath,
		"-vn", // No video
		"-acodec", "libmp3lame",
		"-ab", "128k",
		"-ar", "16000", // 16kHz sample rate (good for speech)
		"-ac", "1", // Mono
		"-y", // Overwrite output
		audioPath,
	}

	cmd := exec.CommandContext(ctx, ffmpegPath, args...)

	// Capture stderr for error messages
	var stderr strings.Builder
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("ffmpeg error: %v, stderr: %s", err, stderr.String())
	}

	return audioPath, nil
}

// HasSubtitle checks if a scene already has a subtitle file
func (s *Service) HasSubtitle(scene *models.Scene) bool {
	if scene.Path == "" {
		return false
	}

	ext := filepath.Ext(scene.Path)
	basePath := strings.TrimSuffix(scene.Path, ext)

	// Check all supported subtitle extensions using the centralized SubtitleExts list
	for _, subExt := range video.SubtitleExts {
		subtitlePath := basePath + "." + subExt
		if exists, _ := fsutil.FileExists(subtitlePath); exists {
			return true
		}

		// Check for language-specific subtitles (e.g., video.en.srt, video.zh.vtt)
		matches, err := filepath.Glob(basePath + ".*." + subExt)
		if err == nil && len(matches) > 0 {
			return true
		}
	}
	return false
}

// TestConnection tests the connection to the Whisper service
func (s *Service) TestConnection(ctx context.Context) error {
	s.mutex.RLock()
	client := s.whisperClient
	s.mutex.RUnlock()

	if client == nil {
		return ErrSubtitleDisabled
	}

	return client.HealthCheck(ctx)
}
